services:
  postgres:
    image: postgres:15
    container_name: containertrack_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sam123
      POSTGRES_DB: containertrack_database
    ports:
      - "5432:5432"
    volumes:
      - containertrack_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d containertrack_database"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: containertrack_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:sam123@postgres:5432/containertrack_database?schema=public
      DIRECT_URL: postgresql://postgres:sam123@postgres:5432/containertrack_database?schema=public
      JWT_SECRET: 1732123gohj1l23g12t30128o3123y1231g2g381723ybcaosifcasfjahuisfb1231g2g381723ybcaosifcasfjahuisfb
      JWT_EXPIRES_IN: 1d
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

volumes:
  containertrack_postgres_data: